import { BaseSeeder } from '@adonisjs/lucid/seeders';
import Framework from '#models/framework';
import Control from '#models/control';
import ControlMapping from '#models/control_mapping';
import { PCI_DSS_DESCRIPTIONS } from './pci_dss_descriptions.js';
const D = 'preventive';
const DET = 'detective';
const COR = 'corrective';
const FRAMEWORKS = [
    {
        name: 'ISO 27001',
        version: '2022',
        description: 'Information security management systems',
        controls: [
            { code: 'A.5.1', title: 'Policies for information security', domain: 'Organizational', type: D },
            { code: 'A.5.2', title: 'Information security roles and responsibilities', domain: 'Organizational', type: D },
            { code: 'A.8.1', title: 'User endpoint devices', domain: 'Technological', type: D },
            { code: 'A.8.5', title: 'Secure authentication', domain: 'Technological', type: D },
            { code: 'A.8.24', title: 'Use of cryptography', domain: 'Technological', type: D },
        ],
    },
    {
        name: 'SOC 2',
        version: '2017',
        description: 'Trust Services Criteria',
        controls: [
            { code: 'CC1.1', title: 'COSO principle — integrity and ethical values', domain: 'Common Criteria', type: D },
            { code: 'CC6.1', title: 'Logical and physical access controls', domain: 'Common Criteria', type: D },
            { code: 'CC7.2', title: 'Detection of security events', domain: 'Common Criteria', type: DET },
            { code: 'CC8.1', title: 'Change management', domain: 'Common Criteria', type: D },
        ],
    },
    {
        name: 'ISO 42001',
        version: '2023',
        description: 'AI management system',
        controls: [
            { code: 'A.5.1', title: 'AI policy', domain: 'Governance', type: D },
            { code: 'A.6.2', title: 'AI roles and responsibilities', domain: 'Governance', type: D },
            { code: 'A.8.1', title: 'AI system impact assessment', domain: 'Operations', type: DET },
        ],
    },
    {
        name: 'GDPR',
        version: '2016/679',
        description: 'General Data Protection Regulation basics',
        controls: [
            { code: 'Art.5', title: 'Principles relating to processing of personal data', domain: 'Principles', type: D },
            { code: 'Art.25', title: 'Data protection by design and by default', domain: 'Rights', type: D },
            { code: 'Art.32', title: 'Security of processing', domain: 'Security', type: D },
            { code: 'Art.33', title: 'Notification of a personal data breach', domain: 'Breach', type: COR },
        ],
    },
    {
        name: 'PCI DSS',
        version: 'v4.0',
        description: 'Payment Card Industry Data Security Standard',
        controls: [
            { code: 'REQ-1', title: 'Install and Maintain Network Security Controls', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.1', title: 'Processes and mechanisms for installing and maintaining network security controls are defined and understood.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.1.1', title: 'All security policies and operational procedures that are identified in Requirement 1 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.1.2', title: 'Roles and responsibilities for performing activities in Requirement 1 are documented, assigned, and understood.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.2', title: 'Network security controls (NSCs) are configured and maintained.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.2.1', title: 'Configuration standards for NSC rulesets are defined, implemented, and maintained.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.2.2', title: 'All changes to network connections and to configurations of NSCs are approved and managed in accordance with the change control process defined at Requirement 6.5.1.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.2.3', title: 'An accurate network diagram(s) is maintained that shows all connections between the CDE and other networks, including any wireless networks.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.2.4', title: 'An accurate data-flow diagram(s) is maintained that shows all account data flows across systems and networks, updated as needed upon changes to the environment.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.2.5', title: 'All services, protocols, and ports allowed are identified, approved, and have a defined business need.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.2.6', title: 'Security features are defined and implemented for all services, protocols, and ports that are in use and considered to be insecure, such that the risk is mitigated.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.2.7', title: 'Configurations of NSCs are reviewed at least once every six months to confirm they are relevant and effective.', domain: 'Requirement 1: Network Security Controls', type: DET },
            { code: 'REQ-1.2.8', title: 'Configuration files for NSCs are secured from unauthorized access and kept consistent with active network configurations.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.3', title: 'Network access to and from the cardholder data environment is restricted.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.3.1', title: 'Inbound traffic to the CDE is restricted to only traffic that is necessary; all other traffic is specifically denied.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.3.2', title: 'Outbound traffic from the CDE is restricted to only traffic that is necessary; all other traffic is specifically denied.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.3.3', title: 'NSCs are installed between all wireless networks and the CDE, regardless of whether the wireless network is a CDE, such that all wireless traffic into the CDE is denied by default.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.4', title: 'Network connections between trusted and untrusted networks are controlled.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.4.1', title: 'NSCs are implemented between trusted and untrusted networks.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.4.2', title: 'Inbound traffic from untrusted networks to trusted networks is restricted to authorized services, stateful responses, and all other traffic is denied.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.4.3', title: 'Anti-spoofing measures are implemented to detect and block forged source IP addresses from entering the trusted network.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.4.4', title: 'System components that store cardholder data are not directly accessible from untrusted networks.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.4.5', title: 'The disclosure of internal IP addresses and routing information is limited to only authorized parties.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.5', title: 'Risks to the CDE from computing devices that are able to connect to both untrusted networks and the CDE are mitigated.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-1.5.1', title: 'Security controls are implemented on any computing devices, including company- and employee-owned devices, that connect to both untrusted networks (including the Internet) and the CDE.', domain: 'Requirement 1: Network Security Controls', type: D },
            { code: 'REQ-2', title: 'Apply Secure Configurations to All System Components', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.1', title: 'Processes and mechanisms for applying secure configurations to all system components are defined and understood.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.1.1', title: 'All security policies and operational procedures that are identified in Requirement 2 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.1.2', title: 'Roles and responsibilities for performing activities in Requirement 2 are documented, assigned, and understood.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.2', title: 'System components are configured and managed securely.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.2.1', title: 'Configuration standards covering all system components are developed, implemented, and maintained.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.2.2', title: 'Vendor default accounts are managed — default passwords changed or accounts removed/disabled.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.2.3', title: 'Primary functions with different security levels on the same component are isolated or secured to the level required by the highest-security function.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.2.4', title: 'Only necessary services, protocols, daemons, and functions are enabled; all unnecessary functionality is removed or disabled.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.2.5', title: 'Insecure services, protocols, or daemons have documented business justification and additional security features that reduce the risk.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.2.6', title: 'System security parameters are configured to prevent misuse.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.2.7', title: 'All non-console administrative access is encrypted using strong cryptography.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.3', title: 'Wireless environments are configured and managed securely.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.3.1', title: 'For wireless environments connected to the CDE or transmitting account data, all wireless vendor defaults are changed at installation or are confirmed to be secure.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-2.3.2', title: 'For wireless environments connected to the CDE or transmitting account data, wireless encryption keys are changed when personnel leave or when keys are suspected compromised.', domain: 'Requirement 2: Secure Configurations', type: D },
            { code: 'REQ-3', title: 'Protect Stored Account Data', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.1', title: 'Processes and mechanisms for protecting stored account data are defined and understood.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.1.1', title: 'All security policies and operational procedures that are identified in Requirement 3 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.1.2', title: 'Roles and responsibilities for performing activities in Requirement 3 are documented, assigned, and understood.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.2', title: 'Storage of account data is kept to a minimum.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.2.1', title: 'Account data storage is kept to a minimum through implementation of data retention and disposal policies, procedures, and processes.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.3', title: 'Sensitive authentication data (SAD) is not stored after authorization.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.3.1', title: 'SAD is not stored after authorization, even if encrypted. All sensitive authentication data received is rendered unrecoverable upon completion of the authorization process.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.3.1.1', title: 'The full contents of any track are not stored upon completion of the authorization process.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.3.1.2', title: 'The card verification code is not stored upon completion of the authorization process.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.3.1.3', title: 'The personal identification number (PIN) and the PIN block are not stored upon completion of the authorization process.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.3.2', title: 'SAD that is stored electronically prior to completion of authorization is encrypted using strong cryptography.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.3.3', title: 'Additional requirement for issuers: Any storage of sensitive authentication data is limited to legitimate business need and encrypted using strong cryptography.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.4', title: 'Access to displays of full PAN and ability to copy PAN are restricted.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.4.1', title: 'PAN is masked when displayed — the BIN and last four digits are the maximum number of digits to be displayed.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.4.2', title: 'When using remote-access technologies, technical controls prevent copy and/or relocation of PAN for all personnel, except for those with explicit authorization.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.5', title: 'Primary account number (PAN) is secured wherever it is stored.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.5.1', title: 'PAN is rendered unreadable anywhere it is stored by using one-way hashes, truncation, index tokens, or strong cryptography.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.5.1.1', title: 'Hashes used to render PAN unreadable are keyed cryptographic hashes of the entire PAN, with associated key-management processes and procedures.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.5.1.2', title: 'Disk-level or partition-level encryption used to render PAN unreadable is implemented only on removable media or with an additional mechanism meeting Requirement 3.5.1.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.5.1.3', title: 'Disk-level or partition-level encryption for PAN is managed with separate logical access and decryption keys not associated with user accounts.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.6', title: 'Cryptographic keys used to protect stored account data are secured.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.6.1', title: 'Procedures are defined and implemented to protect cryptographic keys used to protect stored account data against disclosure and misuse.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.6.1.1', title: 'Additional requirement for service providers only: A documented description of the cryptographic architecture is maintained including algorithms, protocols, keys, HSMs, and KMS inventory.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.6.1.2', title: 'Secret and private keys used to protect stored account data are stored encrypted, within an SCD, or as key components at all times.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.6.1.3', title: 'Access to cleartext cryptographic key components is restricted to the fewest number of custodians necessary.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.6.1.4', title: 'Cryptographic keys are stored in the fewest possible locations.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7', title: 'Where cryptography is used to protect stored account data, key management processes and procedures covering all aspects of the key lifecycle are defined and implemented.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.1', title: 'Key-management policies and procedures are implemented to include generation of strong cryptographic keys used to protect stored account data.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.2', title: 'Key-management policies and procedures are implemented to include secure distribution of cryptographic keys used to protect stored account data.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.3', title: 'Key-management policies and procedures are implemented to include secure storage of cryptographic keys used to protect stored account data.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.4', title: 'Key management policies and procedures are implemented for cryptographic key changes for keys that have reached the end of their cryptoperiod.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.5', title: 'Key management policies and procedures are implemented to include the retirement, replacement, or destruction of keys used to protect stored account data.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.6', title: 'Where manual cleartext cryptographic key-management operations are performed by personnel, key-management policies and procedures are implemented including split knowledge and dual control.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.7', title: 'Key management policies and procedures are implemented to include the prevention of unauthorized substitution of cryptographic keys.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.8', title: 'Key management policies and procedures are implemented to include that cryptographic key custodians formally acknowledge their key-custodian responsibilities.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-3.7.9', title: 'Additional requirement for service providers only: Where a service provider shares cryptographic keys with its customers, guidance on secure transmission, storage, and updating of such keys is documented and distributed.', domain: 'Requirement 3: Account Data Protection', type: D },
            { code: 'REQ-4', title: 'Protect Cardholder Data with Strong Cryptography During Transmission Over Open, Public Networks', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-4.1', title: 'Processes and mechanisms for protecting cardholder data with strong cryptography during transmission over open, public networks are defined and understood.', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-4.1.1', title: 'All security policies and operational procedures that are identified in Requirement 4 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-4.1.2', title: 'Roles and responsibilities for performing activities in Requirement 4 are documented, assigned, and understood.', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-4.2', title: 'PAN is protected with strong cryptography during transmission.', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-4.2.1', title: 'Strong cryptography and security protocols are implemented to safeguard PAN during transmission over open, public networks.', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-4.2.1.1', title: 'An inventory of the entity\'s trusted keys and certificates used to protect PAN during transmission is maintained.', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-4.2.1.2', title: 'Wireless networks transmitting PAN or connected to the CDE use industry best practices to implement strong cryptography for authentication and transmission.', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-4.2.2', title: 'PAN is secured with strong cryptography whenever it is sent via end-user messaging technologies.', domain: 'Requirement 4: Cryptography in Transmission', type: D },
            { code: 'REQ-5', title: 'Protect All Systems and Networks from Malicious Software', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.1', title: 'Processes and mechanisms for protecting all systems and networks from malicious software are defined and understood.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.1.1', title: 'All security policies and operational procedures that are identified in Requirement 5 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.1.2', title: 'Roles and responsibilities for performing activities in Requirement 5 are documented, assigned, and understood.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.2', title: 'Malicious software (malware) is prevented, or detected and addressed.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.2.1', title: 'An anti-malware solution(s) is deployed on all system components, except for those system components identified in periodic evaluations that conclude they are not at risk from malware.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.2.2', title: 'The deployed anti-malware solution(s) detects all known types of malware and removes, blocks, or contains all known types of malware.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.2.3', title: 'Any system components that are not at risk for malware are evaluated periodically to include a documented list, threat assessment, and confirmation that anti-malware protection is not required.', domain: 'Requirement 5: Malware Protection', type: DET },
            { code: 'REQ-5.2.3.1', title: 'The frequency of periodic evaluations of system components identified as not at risk for malware is defined in the entity\'s targeted risk analysis per Requirement 12.3.1.', domain: 'Requirement 5: Malware Protection', type: DET },
            { code: 'REQ-5.3', title: 'Anti-malware mechanisms and processes are active, maintained, and monitored.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.3.1', title: 'The anti-malware solution(s) is kept current via automatic updates.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.3.2', title: 'The anti-malware solution(s) performs periodic scans and active or real-time scans, or performs continuous behavioral analysis of systems or processes.', domain: 'Requirement 5: Malware Protection', type: DET },
            { code: 'REQ-5.3.2.1', title: 'If periodic malware scans are performed to meet Requirement 5.3.2, the frequency of scans is defined in the entity\'s targeted risk analysis per Requirement 12.3.1.', domain: 'Requirement 5: Malware Protection', type: DET },
            { code: 'REQ-5.3.3', title: 'For removable electronic media, the anti-malware solution(s) performs automatic scans or continuous behavioral analysis when the media is inserted, connected, or logically mounted.', domain: 'Requirement 5: Malware Protection', type: DET },
            { code: 'REQ-5.3.4', title: 'Audit logs for the anti-malware solution(s) are enabled and retained in accordance with Requirement 10.5.1.', domain: 'Requirement 5: Malware Protection', type: DET },
            { code: 'REQ-5.3.5', title: 'Anti-malware mechanisms cannot be disabled or altered by users, unless specifically documented and authorized by management on a case-by-case basis for a limited time period.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.4', title: 'Anti-phishing mechanisms protect users against phishing attacks.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-5.4.1', title: 'Processes and automated mechanisms are in place to detect and protect personnel against phishing attacks.', domain: 'Requirement 5: Malware Protection', type: D },
            { code: 'REQ-6', title: 'Develop and Maintain Secure Systems and Software', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.1', title: 'Processes and mechanisms for developing and maintaining secure systems and software are defined and understood.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.1.1', title: 'All security policies and operational procedures that are identified in Requirement 6 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.1.2', title: 'Roles and responsibilities for performing activities in Requirement 6 are documented, assigned, and understood.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.2', title: 'Bespoke and custom software are developed securely.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.2.1', title: 'Bespoke and custom software are developed securely, based on industry standards, in accordance with PCI DSS, and incorporating information security throughout the SDLC.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.2.2', title: 'Software development personnel working on bespoke and custom software are trained at least once every 12 months on software security relevant to their job function.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.2.3', title: 'Bespoke and custom software is reviewed prior to being released into production or to customers, to identify and correct potential coding vulnerabilities.', domain: 'Requirement 6: Secure Systems and Software', type: DET },
            { code: 'REQ-6.2.3.1', title: 'If manual code reviews are performed for bespoke and custom software prior to release to production, code changes are reviewed by individuals other than the originating code author and approved by management.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.2.4', title: 'Software engineering techniques or other methods are defined and in use to prevent or mitigate common software attacks and related vulnerabilities in bespoke and custom software.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.3', title: 'Security vulnerabilities are identified and addressed.', domain: 'Requirement 6: Secure Systems and Software', type: DET },
            { code: 'REQ-6.3.1', title: 'Security vulnerabilities are identified and managed using a defined risk-ranking process and industry-recognized sources for security vulnerability information.', domain: 'Requirement 6: Secure Systems and Software', type: DET },
            { code: 'REQ-6.3.2', title: 'An inventory of bespoke and custom software, and third-party software components incorporated into bespoke and custom software is maintained to facilitate vulnerability and patch management.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.3.3', title: 'All system components are protected from known vulnerabilities by installing applicable security patches/updates — critical vulnerabilities within one month of release.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.4', title: 'Public-facing web applications are protected against attacks.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.4.1', title: 'For public-facing web applications, new threats and vulnerabilities are addressed on an ongoing basis and these applications are protected against known attacks.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.4.2', title: 'For public-facing web applications, an automated technical solution is deployed that continually detects and prevents web-based attacks.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.4.3', title: 'All payment page scripts that are loaded and executed in the consumer\'s browser are managed via authorization, integrity assurance, and inventory.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.5', title: 'Changes to all system components are managed securely.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.5.1', title: 'Changes to all system components in the production environment are made according to established procedures that include security impact documentation, change approval, and testing.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.5.2', title: 'Upon completion of a significant change, all applicable PCI DSS requirements are confirmed to be in place on all new or changed systems and networks, and documentation is updated as applicable.', domain: 'Requirement 6: Secure Systems and Software', type: DET },
            { code: 'REQ-6.5.3', title: 'Pre-production environments are separated from production environments and the separation is enforced with access controls.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.5.4', title: 'Roles and functions are separated between production and pre-production environments to provide accountability such that only reviewed and approved changes are deployed.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.5.5', title: 'Live PANs are not used in pre-production environments, except where those environments are included in the CDE and protected in accordance with all applicable PCI DSS requirements.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-6.5.6', title: 'Test data and test accounts are removed from system components before the system goes into production.', domain: 'Requirement 6: Secure Systems and Software', type: D },
            { code: 'REQ-7', title: 'Restrict Access to System Components and Cardholder Data by Business Need to Know', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.1', title: 'Processes and mechanisms for restricting access to system components and cardholder data by business need to know are defined and understood.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.1.1', title: 'All security policies and operational procedures that are identified in Requirement 7 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.1.2', title: 'Roles and responsibilities for performing activities in Requirement 7 are documented, assigned, and understood.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.2', title: 'Access to system components and data is appropriately defined and assigned.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.2.1', title: 'An access control model is defined and includes granting access based on business and access needs and the principle of least privilege.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.2.2', title: 'Access is assigned to users, including privileged users, based on job classification and function and least privileges necessary to perform job responsibilities.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.2.3', title: 'Required privileges are approved by authorized personnel.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.2.4', title: 'All user accounts and related access privileges, including third-party/vendor accounts, are reviewed at least once every six months.', domain: 'Requirement 7: Access Control', type: DET },
            { code: 'REQ-7.2.5', title: 'All application and system accounts and related access privileges are assigned and managed based on the least privileges necessary for the operability of the system or application.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.2.5.1', title: 'All access by application and system accounts and related access privileges are reviewed periodically at the frequency defined in the entity\'s targeted risk analysis.', domain: 'Requirement 7: Access Control', type: DET },
            { code: 'REQ-7.2.6', title: 'All user access to query repositories of stored cardholder data is restricted via applications or programmatic methods based on user roles and least privileges.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.3', title: 'Access to system components and data is managed via an access control system(s).', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.3.1', title: 'An access control system(s) is in place that restricts access based on a user\'s need to know and covers all system components.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.3.2', title: 'The access control system(s) is configured to enforce permissions assigned to individuals, applications, and systems based on job classification and function.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-7.3.3', title: 'The access control system(s) is set to "deny all" by default.', domain: 'Requirement 7: Access Control', type: D },
            { code: 'REQ-8', title: 'Identify Users and Authenticate Access to System Components', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.1', title: 'Processes and mechanisms for identifying users and authenticating access to system components are defined and understood.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.1.1', title: 'All security policies and operational procedures that are identified in Requirement 8 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.1.2', title: 'Roles and responsibilities for performing activities in Requirement 8 are documented, assigned, and understood.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2', title: 'User identification and related accounts for users and administrators are strictly managed throughout an account\'s lifecycle.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2.1', title: 'All users are assigned a unique ID before access to system components or cardholder data is allowed.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2.2', title: 'Group, shared, or generic IDs, or other shared authentication credentials are only used when necessary on an exception basis, and are managed with additional controls.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2.3', title: 'Additional requirement for service providers only: Service providers with remote access to customer premises use unique authentication factors for each customer premises.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2.4', title: 'Addition, deletion, and modification of user IDs, authentication factors, and other identifier objects are managed as follows: authorized with appropriate approval, implemented with only the privileges specified.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2.5', title: 'Access for terminated users is immediately revoked upon termination.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2.6', title: 'Inactive user accounts are removed or disabled within 90 days of inactivity.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2.7', title: 'Accounts used by third parties to access, support, or maintain system components via remote access are enabled only when needed and monitored when in use.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.2.8', title: 'If a user session has been idle for more than 15 minutes, the user is required to re-authenticate to re-activate the terminal or session.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3', title: 'Strong authentication for users and administrators is established and managed.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.1', title: 'All user access to system components for users and administrators is authenticated via at least one authentication factor: something you know, something you have, or something you are.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.2', title: 'Strong cryptography is used to render all authentication factors unreadable during transmission and storage on all system components.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.3', title: 'User identity is verified before modifying any authentication factor.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.4', title: 'Invalid authentication attempts are limited by locking out the user ID after not more than 10 attempts for a minimum of 30 minutes or until the user\'s identity is confirmed.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.5', title: 'If passwords/passphrases are used as authentication factors, they are set to a unique value for first-time use and upon reset, and forced to be changed immediately after the first use.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.6', title: 'If passwords/passphrases are used as authentication factors, they meet a minimum length of 12 characters with both numeric and alphabetic characters.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.7', title: 'Individuals are not allowed to submit a new password/passphrase that is the same as any of the last four passwords/passphrases used.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.8', title: 'Authentication policies and procedures are documented and communicated to all users including guidance on strong authentication factors and instructions to change compromised passwords.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.9', title: 'If passwords/passphrases are used as the only authentication factor for user access, then passwords/passphrases are changed at least once every 90 days or accounts are dynamically analyzed.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.10', title: 'Additional requirement for service providers only: If passwords/passphrases are used as the only authentication factor for customer user access to cardholder data, guidance is provided to customer users.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.10.1', title: 'Additional requirement for service providers only: If passwords/passphrases are used as the only authentication factor for customer user access, passwords/passphrases are changed at least every 90 days or accounts are dynamically analyzed.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.3.11', title: 'Where authentication factors such as physical or logical security tokens, smart cards, or certificates are used, factors are assigned to an individual user and not shared among multiple users.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.4', title: 'Multi-factor authentication (MFA) is implemented to secure access into the CDE.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.4.1', title: 'MFA is implemented for all non-console access into the CDE for personnel with administrative access.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.4.2', title: 'MFA is implemented for all non-console access into the CDE.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.4.3', title: 'MFA is implemented for all remote access originating from outside the entity\'s network that could access or impact the CDE.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.5', title: 'Multi-factor authentication (MFA) systems are configured to prevent misuse.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.5.1', title: 'MFA systems are not susceptible to replay attacks, cannot be bypassed by any users, use at least two different types of authentication factors, and require success of all factors before granting access.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.6', title: 'Use of application and system accounts and associated authentication factors is strictly managed.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.6.1', title: 'If accounts used by systems or applications can be used for interactive login, they are managed with strict controls limiting interactive use to exceptional circumstances with management approval.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.6.2', title: 'Passwords/passphrases for any application and system accounts that can be used for interactive login are not hard coded in scripts, configuration/property files, or bespoke and custom source code.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-8.6.3', title: 'Passwords/passphrases for any application and system accounts are changed periodically and upon suspicion or confirmation of compromise, and are constructed with sufficient complexity.', domain: 'Requirement 8: Authentication and Identity', type: D },
            { code: 'REQ-9', title: 'Restrict Physical Access to Cardholder Data', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.1', title: 'Processes and mechanisms for restricting physical access to cardholder data are defined and understood.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.1.1', title: 'All security policies and operational procedures that are identified in Requirement 9 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.1.2', title: 'Roles and responsibilities for performing activities in Requirement 9 are documented, assigned, and understood.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.2', title: 'Physical access controls manage entry into facilities and systems containing cardholder data.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.2.1', title: 'Appropriate facility entry controls are in place to restrict physical access to systems in the CDE.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.2.1.1', title: 'Individual physical access to sensitive areas within the CDE is monitored with video cameras or physical access control mechanisms, with data stored for at least three months.', domain: 'Requirement 9: Physical Access Controls', type: DET },
            { code: 'REQ-9.2.2', title: 'Physical and/or logical controls are implemented to restrict use of publicly accessible network jacks within the facility.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.2.3', title: 'Physical access to wireless access points, gateways, networking/communications hardware, and telecommunication lines within the facility is restricted.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.2.4', title: 'Access to consoles in sensitive areas is restricted via locking when not in use.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.3', title: 'Physical access for personnel and visitors is authorized and managed.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.3.1', title: 'Procedures are implemented for authorizing and managing physical access of personnel to the CDE, including identifying personnel, managing access changes, revoking identification, and limiting access to the identification system.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.3.1.1', title: 'Physical access to sensitive areas within the CDE for personnel is controlled based on individual job function, with access revoked immediately upon termination.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.3.2', title: 'Procedures are implemented for authorizing and managing visitor access to the CDE, including escort requirements and badge issuance that expires.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.3.3', title: 'Visitor badges or identification are surrendered or deactivated before visitors leave the facility or at the date of expiration.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.3.4', title: 'Visitor logs are used to maintain a physical record of visitor activity within the facility and sensitive areas, retained for at least three months.', domain: 'Requirement 9: Physical Access Controls', type: DET },
            { code: 'REQ-9.4', title: 'Media with cardholder data is securely stored, accessed, distributed, and destroyed.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.4.1', title: 'All media with cardholder data is physically secured.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.4.1.1', title: 'Offline media backups with cardholder data are stored in a secure location.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.4.1.2', title: 'The security of the offline media backup location(s) with cardholder data is reviewed at least once every 12 months.', domain: 'Requirement 9: Physical Access Controls', type: DET },
            { code: 'REQ-9.4.2', title: 'All media with cardholder data is classified in accordance with the sensitivity of the data.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.4.3', title: 'Media with cardholder data sent outside the facility is logged, secured with a trusted courier, and tracked offsite.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.4.4', title: 'Management approves all media with cardholder data that is moved outside the facility.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.4.5', title: 'Inventory logs of all electronic media with cardholder data are maintained.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.4.5.1', title: 'Inventories of electronic media with cardholder data are conducted at least once every 12 months.', domain: 'Requirement 9: Physical Access Controls', type: DET },
            { code: 'REQ-9.4.6', title: 'Hard-copy materials with cardholder data are destroyed when no longer needed by cross-cut shredding, incineration, or pulping, with materials stored securely prior to destruction.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.4.7', title: 'Electronic media with cardholder data is destroyed when no longer needed by destroying the media or rendering the cardholder data unrecoverable.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.5', title: 'Point of interaction (POI) devices are protected from tampering and unauthorized substitution.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.5.1', title: 'POI devices that capture payment card data via direct physical interaction with the payment card form factor are protected from tampering and unauthorized substitution.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.5.1.1', title: 'An up-to-date list of POI devices is maintained including make, model, location, and device serial number or other methods of unique identification.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-9.5.1.2', title: 'POI device surfaces are periodically inspected to detect tampering and unauthorized substitution.', domain: 'Requirement 9: Physical Access Controls', type: DET },
            { code: 'REQ-9.5.1.2.1', title: 'The frequency of periodic POI device inspections and the type of inspections performed is defined in the entity\'s targeted risk analysis per Requirement 12.3.1.', domain: 'Requirement 9: Physical Access Controls', type: DET },
            { code: 'REQ-9.5.1.3', title: 'Training is provided for personnel in POI environments to be aware of attempted tampering or replacement of POI devices, including verifying identity of third-party repair personnel.', domain: 'Requirement 9: Physical Access Controls', type: D },
            { code: 'REQ-10', title: 'Log and Monitor All Access to System Components and Cardholder Data', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.1', title: 'Processes and mechanisms for logging and monitoring all access to system components and cardholder data are defined and understood.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.1.1', title: 'All security policies and operational procedures that are identified in Requirement 10 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.1.2', title: 'Roles and responsibilities for performing activities in Requirement 10 are documented, assigned, and understood.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.2', title: 'Audit logs are implemented to support the detection of anomalies and suspicious activity, and the forensic analysis of events.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.1', title: 'Audit logs are enabled and active for all system components and cardholder data.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.1.1', title: 'Audit logs capture all individual user access to cardholder data.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.1.2', title: 'Audit logs capture all actions taken by any individual with administrative access, including any interactive use of application or system accounts.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.1.3', title: 'Audit logs capture all access to audit logs.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.1.4', title: 'Audit logs capture all invalid logical access attempts.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.1.5', title: 'Audit logs capture all changes to identification and authentication credentials including creation of new accounts, elevation of privileges, and changes to accounts with administrative access.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.1.6', title: 'Audit logs capture all initialization of new audit logs, and all starting, stopping, or pausing of the existing audit logs.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.1.7', title: 'Audit logs capture all creation and deletion of system-level objects.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.2.2', title: 'Audit logs record user identification, event type, date and time, success/failure, origination of event, and identity or name of affected data, system component, resource, or service.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.3', title: 'Audit logs are protected from destruction and unauthorized modifications.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.3.1', title: 'Read access to audit log files is limited to those with a job-related need.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.3.2', title: 'Audit log files are protected to prevent modifications by individuals.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.3.3', title: 'Audit log files, including those for external facing technologies, are promptly backed up to a secure, central, internal log server(s) or other media that is difficult to modify.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.3.4', title: 'File integrity monitoring or change-detection mechanisms are used on audit logs to ensure that existing log data cannot be changed without generating alerts.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.4', title: 'Audit logs are reviewed to identify anomalies or suspicious activity.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.4.1', title: 'The following audit logs are reviewed at least once daily: all security events, logs of system components storing/processing/transmitting CHD/SAD, critical system components, and security function servers.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.4.1.1', title: 'Automated mechanisms are used to perform audit log reviews.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.4.2', title: 'Logs of all other system components not covered under Requirement 10.4.1 are reviewed periodically.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.4.2.1', title: 'The frequency of periodic log reviews for other system components is defined in the entity\'s targeted risk analysis per Requirement 12.3.1.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.4.3', title: 'Exceptions and anomalies identified during log reviews are addressed.', domain: 'Requirement 10: Logging and Monitoring', type: COR },
            { code: 'REQ-10.5', title: 'Retain audit log history for at least 12 months, with at least the most recent three months available for immediate analysis.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.5.1', title: 'Audit log history is retained for at least 12 months, with at least the most recent three months available for immediate analysis.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.6', title: 'Time-synchronization mechanisms support consistent time settings across all systems.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.6.1', title: 'System clocks and time are synchronized using time-synchronization technology across all system components.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.6.2', title: 'Systems are configured to the correct and consistent time using designated central time server(s) with accepted external time sources.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.6.3', title: 'Time synchronization settings and data are protected with restricted access and logging of any changes to time data.', domain: 'Requirement 10: Logging and Monitoring', type: D },
            { code: 'REQ-10.7', title: 'Failures of critical security controls are detected, reported, and responded to promptly.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.7.1', title: 'Additional requirement for service providers only: Failures of critical security control systems are detected, alerted, and addressed promptly including network security controls, IDS/IPS, FIM, anti-malware, and access controls.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.7.2', title: 'Failures of critical security control systems are detected, alerted, and addressed promptly, including network security controls, IDS/IPS, change-detection, anti-malware, physical and logical access controls.', domain: 'Requirement 10: Logging and Monitoring', type: DET },
            { code: 'REQ-10.7.3', title: 'Failures of any critical security control systems are responded to promptly, including restoring security functions, identifying the cause, addressing security issues, and resuming monitoring.', domain: 'Requirement 10: Logging and Monitoring', type: COR },
            { code: 'REQ-11', title: 'Test Security of Systems and Networks Regularly', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.1', title: 'Processes and mechanisms for regularly testing security of systems and networks are defined and understood.', domain: 'Requirement 11: Security Testing', type: D },
            { code: 'REQ-11.1.1', title: 'All security policies and operational procedures that are identified in Requirement 11 are documented, kept up to date, in use, and known to all affected parties.', domain: 'Requirement 11: Security Testing', type: D },
            { code: 'REQ-11.1.2', title: 'Roles and responsibilities for performing activities in Requirement 11 are documented, assigned, and understood.', domain: 'Requirement 11: Security Testing', type: D },
            { code: 'REQ-11.2', title: 'Wireless access points are identified and monitored, and unauthorized wireless access points are addressed.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.2.1', title: 'Authorized and unauthorized wireless access points are managed, tested at least once every three months, with alerts generated for unauthorized devices.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.2.2', title: 'An inventory of authorized wireless access points is maintained including a documented business justification for each.', domain: 'Requirement 11: Security Testing', type: D },
            { code: 'REQ-11.3', title: 'External and internal vulnerabilities are regularly identified, prioritized, and addressed.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.3.1', title: 'Internal vulnerability scans are performed at least once every three months with resolution of high-risk and critical vulnerabilities and rescans to confirm resolution.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.3.1.1', title: 'All other applicable vulnerabilities not ranked high-risk or critical are addressed based on the risk defined in the entity\'s targeted risk analysis per Requirement 12.3.1.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.3.1.2', title: 'Internal vulnerability scans are performed via authenticated scanning with sufficient privileges, with documented exceptions for systems that cannot accept credentials.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.3.1.3', title: 'Internal vulnerability scans are performed after any significant change with resolution of high-risk and critical vulnerabilities and rescans as needed.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.3.2', title: 'External vulnerability scans are performed at least once every three months by a PCI SSC Approved Scanning Vendor (ASV) with all vulnerabilities resolved per ASV Program Guide.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.3.2.1', title: 'External vulnerability scans are performed after any significant change with resolution of CVSS 4.0 or higher vulnerabilities and rescans as needed.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.4', title: 'External and internal penetration testing is regularly performed, and exploitable vulnerabilities and security weaknesses are corrected.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.4.1', title: 'A penetration testing methodology is defined, documented, and implemented covering the entire CDE perimeter, critical systems, application and network layers, and segmentation controls.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.4.2', title: 'Internal penetration testing is performed at least once every 12 months and after any significant infrastructure or application upgrade or change, by a qualified resource.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.4.3', title: 'External penetration testing is performed at least once every 12 months and after any significant infrastructure or application upgrade or change, by a qualified resource.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.4.4', title: 'Exploitable vulnerabilities and security weaknesses found during penetration testing are corrected in accordance with the entity\'s assessment of the risk, and penetration testing is repeated to verify corrections.', domain: 'Requirement 11: Security Testing', type: COR },
            { code: 'REQ-11.4.5', title: 'Penetration tests are performed on segmentation controls at least once every 12 months and after any changes to confirm effectiveness and isolation of the CDE.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.4.6', title: 'Additional requirement for service providers only: Penetration tests are performed on segmentation controls at least once every six months and after any changes.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.4.7', title: 'Additional requirement for service providers only: Multi-tenant service providers support their customers for external penetration testing per Requirements 11.4.3 and 11.4.4.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.5', title: 'Network intrusions and unexpected file changes are detected and responded to.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.5.1', title: 'Intrusion-detection and/or intrusion-prevention techniques are used to monitor all traffic at the CDE perimeter and critical points in the CDE with up-to-date signatures.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.5.1.1', title: 'Additional requirement for service providers only: IDS/IPS detects, alerts on, prevents, and addresses covert malware communication channels.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.5.2', title: 'A change-detection mechanism is deployed to alert on unauthorized modification of critical files with critical file comparisons performed at least once weekly.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.6', title: 'Unauthorized changes on payment pages are detected and responded to.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-11.6.1', title: 'A change- and tamper-detection mechanism is deployed to alert on unauthorized modification to HTTP headers and script contents of payment pages received by the consumer browser.', domain: 'Requirement 11: Security Testing', type: DET },
            { code: 'REQ-12', title: 'Support Information Security with Organizational Policies and Programs', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.1', title: 'A comprehensive information security policy that governs and provides direction for protection of the entity\'s information assets is known and current.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.1.1', title: 'An overall information security policy is established, published, maintained, and disseminated to all relevant personnel, vendors, and business partners.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.1.2', title: 'The information security policy is reviewed at least once every 12 months and updated as needed to reflect changes to business objectives or risks to the environment.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.1.3', title: 'The security policy clearly defines information security roles and responsibilities for all personnel who acknowledge their responsibilities.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.1.4', title: 'Responsibility for information security is formally assigned to a CISO or other information security knowledgeable member of executive management.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.2', title: 'Acceptable-use policies for end-user technologies are defined and implemented.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.2.1', title: 'Acceptable use policies for end-user technologies are documented and implemented, including explicit approval by authorized parties and a list of approved products.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.3', title: 'Risks to the cardholder data environment are formally identified, evaluated, and managed.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.3.1', title: 'For each PCI DSS requirement specifying a targeted risk analysis, the analysis is documented and includes assets, threats, likelihood, impact, and annual review.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.3.2', title: 'A targeted risk analysis is performed for each PCI DSS requirement met with the customized approach, approved by senior management and reviewed annually.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.3.3', title: 'Cryptographic cipher suites and protocols in use are documented and reviewed at least once every 12 months including viability monitoring and remediation plan.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.3.4', title: 'Hardware and software technologies are reviewed at least once every 12 months for security fix support, PCI DSS compliance support, and end-of-life planning.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.4', title: 'PCI DSS compliance is managed.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.4.1', title: 'Additional requirement for service providers only: Executive management establishes responsibility for maintaining PCI DSS compliance and defines a charter for the PCI DSS compliance program.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.4.2', title: 'Additional requirement for service providers only: Reviews are performed at least once every three months to confirm personnel are performing tasks per security policies and procedures.', domain: 'Requirement 12: Policies and Programs', type: DET },
            { code: 'REQ-12.4.2.1', title: 'Additional requirement for service providers only: Reviews per Requirement 12.4.2 are documented including results, remediation actions, and sign-off by the PCI DSS compliance program owner.', domain: 'Requirement 12: Policies and Programs', type: DET },
            { code: 'REQ-12.5', title: 'PCI DSS scope is documented and validated.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.5.1', title: 'An inventory of system components in scope for PCI DSS including description of function/use is maintained and kept current.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.5.2', title: 'PCI DSS scope is documented and confirmed at least once every 12 months and upon significant change, covering data flows, account data locations, and segmentation controls.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.5.2.1', title: 'Additional requirement for service providers only: Service providers document and confirm PCI DSS scope at least once every six months and upon significant change.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.5.3', title: 'Additional requirement for service providers only: Significant changes to organizational structure result in a documented review of impact to PCI DSS scope communicated to executive management.', domain: 'Requirement 12: Policies and Programs', type: DET },
            { code: 'REQ-12.6', title: 'Security awareness education is an ongoing activity.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.6.1', title: 'A formal security awareness program is implemented to make all personnel aware of the information security policy and their role in protecting cardholder data.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.6.2', title: 'The security awareness program is reviewed at least once every 12 months and updated to address new threats and vulnerabilities.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.6.3', title: 'Personnel receive security awareness training upon hire and at least once every 12 months using multiple methods with annual written acknowledgment.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.6.3.1', title: 'Security awareness training includes awareness of phishing, related attacks, and social engineering threats to cardholder data and sensitive authentication data.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.6.3.2', title: 'Security awareness training includes awareness about the acceptable use of end-user technologies per Requirement 12.2.1.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.7', title: 'Personnel are screened to reduce risks from insider threats.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.7.1', title: 'Potential personnel who will have access to the CDE are screened prior to hire within the constraints of local laws to minimize insider threat risk.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.8', title: 'Risk to information assets associated with third-party service provider (TPSP) relationships is managed.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.8.1', title: 'A list of all TPSPs with which account data is shared or that could affect security is maintained including description of services provided.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.8.2', title: 'Written agreements with all TPSPs include acknowledgment that TPSPs are responsible for the security of account data they possess, store, process, or transmit.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.8.3', title: 'An established process for engaging TPSPs is implemented including proper due diligence prior to engagement.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.8.4', title: 'A program is implemented to monitor TPSPs\' PCI DSS compliance status at least once every 12 months.', domain: 'Requirement 12: Policies and Programs', type: DET },
            { code: 'REQ-12.8.5', title: 'Information is maintained about which PCI DSS requirements are managed by each TPSP, which by the entity, and any that are shared responsibilities.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.9', title: 'TPSPs support their customers\' PCI DSS compliance.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.9.1', title: 'Additional requirement for service providers only: TPSPs provide written agreements to customers acknowledging responsibility for security of account data they store, process, or transmit.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.9.2', title: 'Additional requirement for service providers only: TPSPs support customers\' requests for PCI DSS compliance status information and shared responsibility details upon request.', domain: 'Requirement 12: Policies and Programs', type: D },
            { code: 'REQ-12.10', title: 'Suspected and confirmed security incidents that could impact the CDE are responded to immediately.', domain: 'Requirement 12: Policies and Programs', type: COR },
            { code: 'REQ-12.10.1', title: 'An incident response plan exists and is ready to be activated for suspected or confirmed security incidents including roles, containment, recovery, legal requirements, and coverage of all critical system components.', domain: 'Requirement 12: Policies and Programs', type: COR },
            { code: 'REQ-12.10.2', title: 'At least once every 12 months, the security incident response plan is reviewed, content is updated as needed, and tested including all elements listed in Requirement 12.10.1.', domain: 'Requirement 12: Policies and Programs', type: COR },
            { code: 'REQ-12.10.3', title: 'Specific personnel are designated to be available on a 24/7 basis to respond to suspected or confirmed security incidents.', domain: 'Requirement 12: Policies and Programs', type: COR },
            { code: 'REQ-12.10.4', title: 'Personnel responsible for responding to suspected and confirmed security incidents are appropriately and periodically trained on their responsibilities.', domain: 'Requirement 12: Policies and Programs', type: COR },
            { code: 'REQ-12.10.4.1', title: 'Frequency of periodic training for incident response personnel is defined in the entity\'s targeted risk analysis per Requirement 12.3.1.', domain: 'Requirement 12: Policies and Programs', type: COR },
            { code: 'REQ-12.10.5', title: 'The security incident response plan includes monitoring and responding to alerts from security monitoring systems including IDS/IPS, network security controls, change-detection mechanisms, and unauthorized wireless APs.', domain: 'Requirement 12: Policies and Programs', type: COR },
            { code: 'REQ-12.10.6', title: 'The security incident response plan is modified and evolved according to lessons learned and to incorporate industry developments.', domain: 'Requirement 12: Policies and Programs', type: COR },
            { code: 'REQ-12.10.7', title: 'Incident response procedures are in place upon detection of stored PAN anywhere not expected, including retrieval, deletion, migration, and remediation of data leaks.', domain: 'Requirement 12: Policies and Programs', type: COR },
        ],
    },
    {
        name: 'Custom',
        version: '1.0',
        description: 'Custom organizational framework',
        controls: [
            { code: 'CUST-01', title: 'Custom security baseline', domain: 'Custom', type: D },
            { code: 'CUST-02', title: 'Custom access review', domain: 'Custom', type: DET },
        ],
    },
];
export default class FrameworkSeeder extends BaseSeeder {
    async run() {
        const controlIdByCode = new Map();
        for (const fw of FRAMEWORKS) {
            const framework = await Framework.updateOrCreate({ name: fw.name }, { name: fw.name, version: fw.version, description: fw.description, status: 'active' });
            for (const c of fw.controls) {
                const control = await Control.updateOrCreate({ frameworkId: framework.id, controlCode: c.code }, {
                    frameworkId: framework.id,
                    controlCode: c.code,
                    controlTitle: c.title,
                    controlDescription: PCI_DSS_DESCRIPTIONS[c.code] ?? c.title,
                    domain: c.domain,
                    evidenceRequired: 'Policy document or configuration evidence',
                    controlType: fw.name === 'PCI DSS' ? null : (c.type ?? null),
                });
                controlIdByCode.set(`${fw.name}:${c.code}`, control.id);
            }
        }
        const isoAccess = controlIdByCode.get('ISO 27001:A.8.5');
        const socAccess = controlIdByCode.get('SOC 2:CC6.1');
        if (isoAccess && socAccess) {
            await ControlMapping.updateOrCreate({ sourceControlId: isoAccess, targetControlId: socAccess }, { sourceControlId: isoAccess, targetControlId: socAccess, mappingType: 'equivalent' });
        }
        const gdprSecurity = controlIdByCode.get('GDPR:Art.32');
        if (isoAccess && gdprSecurity) {
            await ControlMapping.updateOrCreate({ sourceControlId: isoAccess, targetControlId: gdprSecurity }, { sourceControlId: isoAccess, targetControlId: gdprSecurity, mappingType: 'related' });
        }
        console.log('✅  Frameworks, controls, and mappings seeded.');
    }
}
//# sourceMappingURL=framework_seeder.js.map