import { BaseSeeder } from '@adonisjs/lucid/seeders';
import db from '@adonisjs/lucid/services/db';
const CLAUSES = [
    { clause_number: '4', title: 'Context of the Organization', description: 'Understanding the organization and its context, interested parties, scope of ISMS, and the ISMS itself.', sort_order: 1 },
    { clause_number: '4.1', title: 'Understanding the organization and its context', description: 'The organization shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended outcome(s) of its information security management system.', sort_order: 1, parent_number: '4' },
    { clause_number: '4.2', title: 'Understanding the needs and expectations of interested parties', description: 'The organization shall determine: a) interested parties that are relevant to the information security management system; b) the relevant requirements of these interested parties; c) which of these requirements will be addressed through the information security management system.', sort_order: 2, parent_number: '4' },
    { clause_number: '4.3', title: 'Determining the scope of the information security management system', description: 'The organization shall determine the boundaries and applicability of the information security management system to establish its scope. When determining this scope, the organization shall consider: a) the external and internal issues referred to in 4.1; b) the requirements referred to in 4.2; c) interfaces and dependencies between activities performed by the organization, and those that are performed by other organizations.', sort_order: 3, parent_number: '4' },
    { clause_number: '4.4', title: 'Information security management system', description: 'The organization shall establish, implement, maintain and continually improve an information security management system, including the processes needed and their interactions, in accordance with the requirements of this document.', sort_order: 4, parent_number: '4' },
    { clause_number: '5', title: 'Leadership', description: 'Leadership and commitment, policy, and organizational roles, responsibilities and authorities.', sort_order: 2 },
    { clause_number: '5.1', title: 'Leadership and commitment', description: 'Top management shall demonstrate leadership and commitment with respect to the information security management system by: a) ensuring the information security policy and the information security objectives are established and are compatible with the strategic direction of the organization; b) ensuring the integration of the information security management system requirements into the organization\'s processes; c) ensuring that the resources needed for the information security management system are available; d) communicating the importance of effective information security management and of conforming to the information security management system requirements; e) ensuring that the information security management system achieves its intended outcome(s); f) directing persons to contribute to the effectiveness of the information security management system; g) promoting continual improvement; h) supporting other relevant management roles to demonstrate their leadership as it applies to their areas of responsibility.', sort_order: 1, parent_number: '5' },
    { clause_number: '5.2', title: 'Policy', description: 'Top management shall establish an information security policy that: a) is appropriate to the purpose of the organization; b) includes information security objectives or provides the framework for setting information security objectives; c) includes a commitment to satisfy applicable requirements related to information security; d) includes a commitment to continual improvement of the information security management system.', sort_order: 2, parent_number: '5' },
    { clause_number: '5.3', title: 'Organizational roles, responsibilities and authorities', description: 'Top management shall ensure that the responsibilities and authorities for roles relevant to information security are assigned and communicated within the organization.', sort_order: 3, parent_number: '5' },
    { clause_number: '6', title: 'Planning', description: 'Actions to address risks and opportunities, information security objectives and planning to achieve them.', sort_order: 3 },
    { clause_number: '6.1', title: 'Actions to address risks and opportunities', description: 'When planning for the information security management system, the organization shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities that need to be addressed.', sort_order: 1, parent_number: '6' },
    { clause_number: '6.1.1', title: 'General', description: 'When planning for the information security management system, the organization shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities that need to be addressed to: a) ensure the information security management system can achieve its intended outcome(s); b) prevent, or reduce, undesired effects; c) achieve continual improvement.', sort_order: 1, parent_number: '6.1' },
    { clause_number: '6.1.2', title: 'Information security risk assessment', description: 'The organization shall define and apply an information security risk assessment process that: a) establishes and maintains information security risk criteria that include: 1) the risk acceptance criteria; 2) criteria for performing information security risk assessments; b) ensures that repeated information security risk assessments produce consistent, valid and comparable results; c) identifies the information security risks; d) analyses the information security risks; e) evaluates the information security risks.', sort_order: 2, parent_number: '6.1' },
    { clause_number: '6.1.3', title: 'Information security risk treatment', description: 'The organization shall define and apply an information security risk treatment process to: a) select appropriate information security risk treatment options, taking account of the risk assessment results; b) determine all controls that are necessary to implement the information security risk treatment option(s) chosen; c) compare the controls determined above with those in Annex A and verify that no necessary controls have been omitted; d) produce a Statement of Applicability; e) formulate an information security risk treatment plan; f) obtain risk owners\' approval of the information security risk treatment plan and acceptance of the residual information security risks.', sort_order: 3, parent_number: '6.1' },
    { clause_number: '6.2', title: 'Information security objectives and planning to achieve them', description: 'The organization shall establish information security objectives at relevant functions and levels. The information security objectives shall: a) be consistent with the information security policy; b) be measurable (if practicable); c) take into account applicable information security requirements, and results from risk assessment and risk treatment; d) be monitored; e) be communicated; f) be updated as appropriate; g) be available as documented information.', sort_order: 2, parent_number: '6' },
    { clause_number: '6.3', title: 'Planning of changes', description: 'When the organization determines the need for changes to the information security management system, the changes shall be carried out in a planned manner.', sort_order: 3, parent_number: '6' },
    { clause_number: '7', title: 'Support', description: 'Resources, competence, awareness, communication, and documented information.', sort_order: 4 },
    { clause_number: '7.1', title: 'Resources', description: 'The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the information security management system.', sort_order: 1, parent_number: '7' },
    { clause_number: '7.2', title: 'Competence', description: 'The organization shall: a) determine the necessary competence of person(s) doing work under its control that affects its information security performance; b) ensure that these persons are competent on the basis of appropriate education, training, or experience; c) where applicable, take actions to acquire the necessary competence, and evaluate the effectiveness of the actions taken; d) retain appropriate documented information as evidence of competence.', sort_order: 2, parent_number: '7' },
    { clause_number: '7.3', title: 'Awareness', description: 'Persons doing work under the organization\'s control shall be aware of: a) the information security policy; b) their contribution to the effectiveness of the information security management system, including the benefits of improved information security performance; c) the implications of not conforming with the information security management system requirements.', sort_order: 3, parent_number: '7' },
    { clause_number: '7.4', title: 'Communication', description: 'The organization shall determine the need for internal and external communications relevant to the information security management system including: a) on what to communicate; b) when to communicate; c) with whom to communicate; d) how to communicate.', sort_order: 4, parent_number: '7' },
    { clause_number: '7.5', title: 'Documented information', description: 'The organization\'s information security management system shall include documented information required by this document and documented information determined by the organization as being necessary for the effectiveness of the information security management system.', sort_order: 5, parent_number: '7' },
    { clause_number: '7.5.1', title: 'General', description: 'The organization\'s information security management system shall include: a) documented information required by this document; b) documented information determined by the organization as being necessary for the effectiveness of the information security management system. NOTE: The extent of documented information for an information security management system can differ from one organization to another due to: 1) the size of organization and its type of activities, processes, products and services; 2) the complexity of processes and their interactions; 3) the competence of persons.', sort_order: 1, parent_number: '7.5' },
    { clause_number: '7.5.2', title: 'Creating and updating', description: 'When creating and updating documented information, the organization shall ensure appropriate: a) identification and description (e.g. a title, date, author, or reference number); b) format (e.g. language, software version, graphics) and media (e.g. paper, electronic); c) review and approval for suitability and adequacy.', sort_order: 2, parent_number: '7.5' },
    { clause_number: '7.5.3', title: 'Control of documented information', description: 'Documented information required by the information security management system and by this document shall be controlled to ensure: a) it is available and suitable for use, where and when it is needed; b) it is adequately protected (e.g. from loss of confidentiality, improper use, or loss of integrity). For the control of documented information, the organization shall address the following activities, as applicable: c) distribution, access, retrieval and use; d) storage and preservation, including the preservation of legibility; e) control of changes (e.g. version control); f) retention and disposition.', sort_order: 3, parent_number: '7.5' },
    { clause_number: '8', title: 'Operation', description: 'Operational planning and control, information security risk assessment and treatment.', sort_order: 5 },
    { clause_number: '8.1', title: 'Operational planning and control', description: 'The organization shall plan, implement, control, monitor and review the processes needed to meet information security requirements, and to implement the actions determined in Clause 6, by: establishing criteria for the processes; implementing control of the processes in accordance with the criteria. Documented information shall be available to the extent necessary to have confidence that the processes have been carried out as planned. The organization shall control planned changes and review the consequences of unintended changes, taking action to mitigate any adverse effects, as necessary. The organization shall ensure that externally provided processes, products or services that are relevant to the information security management system are controlled.', sort_order: 1, parent_number: '8' },
    { clause_number: '8.2', title: 'Information security risk assessment', description: 'The organization shall perform information security risk assessments at planned intervals or when significant changes are proposed or occur, taking account of the criteria established in 6.1.2a). The organization shall retain documented information of the results of the information security risk assessments.', sort_order: 2, parent_number: '8' },
    { clause_number: '8.3', title: 'Information security risk treatment', description: 'The organization shall implement the information security risk treatment plan. The organization shall retain documented information of the results of the information security risk treatment.', sort_order: 3, parent_number: '8' },
    { clause_number: '9', title: 'Performance Evaluation', description: 'Monitoring, measurement, analysis and evaluation; internal audit; and management review.', sort_order: 6 },
    { clause_number: '9.1', title: 'Monitoring, measurement, analysis and evaluation', description: 'The organization shall evaluate the information security performance and the effectiveness of the information security management system.', sort_order: 1, parent_number: '9' },
    { clause_number: '9.2', title: 'Internal audit', description: 'The organization shall conduct internal audits at planned intervals to provide information on whether the information security management system conforms to the organization\'s own requirements for its information security management system and the requirements of this document and is effectively implemented and maintained.', sort_order: 2, parent_number: '9' },
    { clause_number: '9.2.1', title: 'General', description: 'The organization shall conduct internal audits at planned intervals to provide information on whether the information security management system: a) conforms to: 1) the organization\'s own requirements for its information security management system; 2) the requirements of this document; b) is effectively implemented and maintained.', sort_order: 1, parent_number: '9.2' },
    { clause_number: '9.2.2', title: 'Internal audit programme', description: 'The organization shall plan, establish, implement and maintain an audit programme(s), including the frequency, methods, responsibilities, planning requirements and reporting. The audit programme(s) shall take into consideration the importance of the processes concerned and the results of previous audits. The organization shall: a) define the audit criteria and scope for each audit; b) select auditors and conduct audits to ensure objectivity and the impartiality of the audit process; c) ensure that the results of the audits are reported to relevant management; d) retain documented information as evidence of the audit programme(s) and the audit results.', sort_order: 2, parent_number: '9.2' },
    { clause_number: '9.3', title: 'Management review', description: 'Top management shall review the organization\'s information security management system at planned intervals to ensure its continuing suitability, adequacy and effectiveness.', sort_order: 3, parent_number: '9' },
    { clause_number: '9.3.1', title: 'General', description: 'Top management shall review the organization\'s information security management system at planned intervals to ensure its continuing suitability, adequacy and effectiveness.', sort_order: 1, parent_number: '9.3' },
    { clause_number: '9.3.2', title: 'Management review inputs', description: 'The management review shall include consideration of: a) the status of actions from previous management reviews; b) changes in external and internal issues that are relevant to the information security management system; c) changes in needs and expectations of interested parties that are relevant to the information security management system; d) feedback on the information security performance, including trends in: 1) nonconformities and corrective actions; 2) monitoring and measurement results; 3) audit results; 4) fulfilment of information security objectives; e) feedback from interested parties; f) results of risk assessment and status of risk treatment plan; g) opportunities for continual improvement.', sort_order: 2, parent_number: '9.3' },
    { clause_number: '9.3.3', title: 'Management review results', description: 'The results of the management review shall include decisions related to continual improvement opportunities and any need for changes to the information security management system. The organization shall retain documented information as evidence of the results of management reviews.', sort_order: 3, parent_number: '9.3' },
    { clause_number: '10', title: 'Improvement', description: 'Continual improvement and nonconformity and corrective action.', sort_order: 7 },
    { clause_number: '10.1', title: 'Continual improvement', description: 'The organization shall continually improve the suitability, adequacy and effectiveness of the information security management system.', sort_order: 1, parent_number: '10' },
    { clause_number: '10.2', title: 'Nonconformity and corrective action', description: 'When a nonconformity occurs, the organization shall: a) react to the nonconformity, and as applicable: 1) take action to control and correct it; 2) deal with the consequences; b) evaluate the need for action to eliminate the causes of nonconformity, in order that it does not recur or occur elsewhere, by: 1) reviewing the nonconformity; 2) determining the causes of the nonconformity; 3) determining if similar nonconformities exist, or could potentially occur; c) implement any action needed; d) review the effectiveness of any corrective action taken; e) make changes to the information security management system, if necessary. Corrective actions shall be appropriate to the effects of the nonconformities encountered. The organization shall retain documented information as evidence of the nature of the nonconformities and any subsequent actions taken, and the results of any corrective action.', sort_order: 2, parent_number: '10' },
];
const CONTROLS = [
    { control_number: '5.1', category: 'organizational', title: 'Policies for information security', description: 'Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.', sort_order: 1 },
    { control_number: '5.2', category: 'organizational', title: 'Information security roles and responsibilities', description: 'Information security roles and responsibilities shall be defined and allocated according to the organization needs.', sort_order: 2 },
    { control_number: '5.3', category: 'organizational', title: 'Segregation of duties', description: 'Conflicting duties and conflicting areas of responsibility shall be segregated.', sort_order: 3 },
    { control_number: '5.4', category: 'organizational', title: 'Management responsibilities', description: 'Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization.', sort_order: 4 },
    { control_number: '5.5', category: 'organizational', title: 'Contact with authorities', description: 'The organization shall establish and maintain contact with relevant authorities.', sort_order: 5 },
    { control_number: '5.6', category: 'organizational', title: 'Contact with special interest groups', description: 'The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.', sort_order: 6 },
    { control_number: '5.7', category: 'organizational', title: 'Threat intelligence', description: 'Information relating to information security threats shall be collected and analysed to produce threat intelligence.', sort_order: 7 },
    { control_number: '5.8', category: 'organizational', title: 'Information security in project management', description: 'Information security shall be integrated into project management.', sort_order: 8 },
    { control_number: '5.9', category: 'organizational', title: 'Inventory of information and other associated assets', description: 'An inventory of information and other associated assets, including owners, shall be developed and maintained.', sort_order: 9 },
    { control_number: '5.10', category: 'organizational', title: 'Acceptable use of information and other associated assets', description: 'Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.', sort_order: 10 },
    { control_number: '5.11', category: 'organizational', title: 'Return of assets', description: 'Personnel and other interested parties as appropriate shall return all the organization\'s assets in their possession upon change or termination of their employment, contract or agreement.', sort_order: 11 },
    { control_number: '5.12', category: 'organizational', title: 'Classification of information', description: 'Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.', sort_order: 12 },
    { control_number: '5.13', category: 'organizational', title: 'Labelling of information', description: 'An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.', sort_order: 13 },
    { control_number: '5.14', category: 'organizational', title: 'Information transfer', description: 'Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.', sort_order: 14 },
    { control_number: '5.15', category: 'organizational', title: 'Access control', description: 'Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.', sort_order: 15 },
    { control_number: '5.16', category: 'organizational', title: 'Identity management', description: 'The full life cycle of identities shall be managed.', sort_order: 16 },
    { control_number: '5.17', category: 'organizational', title: 'Authentication information', description: 'Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.', sort_order: 17 },
    { control_number: '5.18', category: 'organizational', title: 'Access rights', description: 'Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization\'s topic-specific policy on and rules for access control.', sort_order: 18 },
    { control_number: '5.19', category: 'organizational', title: 'Information security in supplier relationships', description: 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier\'s products or services.', sort_order: 19 },
    { control_number: '5.20', category: 'organizational', title: 'Addressing information security within supplier agreements', description: 'Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.', sort_order: 20 },
    { control_number: '5.21', category: 'organizational', title: 'Managing information security in the ICT supply chain', description: 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.', sort_order: 21 },
    { control_number: '5.22', category: 'organizational', title: 'Monitoring, review and change management of supplier services', description: 'The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.', sort_order: 22 },
    { control_number: '5.23', category: 'organizational', title: 'Information security for use of cloud services', description: 'Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization\'s information security requirements.', sort_order: 23 },
    { control_number: '5.24', category: 'organizational', title: 'Information security incident management planning and preparation', description: 'The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.', sort_order: 24 },
    { control_number: '5.25', category: 'organizational', title: 'Assessment and decision on information security events', description: 'The organization shall assess information security events and decide if they are to be categorized as information security incidents.', sort_order: 25 },
    { control_number: '5.26', category: 'organizational', title: 'Response to information security incidents', description: 'Information security incidents shall be responded to in accordance with the documented procedures.', sort_order: 26 },
    { control_number: '5.27', category: 'organizational', title: 'Learning from information security incidents', description: 'Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.', sort_order: 27 },
    { control_number: '5.28', category: 'organizational', title: 'Collection of evidence', description: 'The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.', sort_order: 28 },
    { control_number: '5.29', category: 'organizational', title: 'Information security during disruption', description: 'The organization shall plan how to maintain information security at an appropriate level during disruption.', sort_order: 29 },
    { control_number: '5.30', category: 'organizational', title: 'ICT readiness for business continuity', description: 'ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.', sort_order: 30 },
    { control_number: '5.31', category: 'organizational', title: 'Legal, statutory, regulatory and contractual requirements', description: 'Legal, statutory, regulatory and contractual requirements relevant to information security and the organization\'s approach to meet these requirements shall be identified, documented and kept up to date.', sort_order: 31 },
    { control_number: '5.32', category: 'organizational', title: 'Intellectual property rights', description: 'The organization shall implement appropriate procedures to protect intellectual property rights.', sort_order: 32 },
    { control_number: '5.33', category: 'organizational', title: 'Protection of records', description: 'Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.', sort_order: 33 },
    { control_number: '5.34', category: 'organizational', title: 'Privacy and protection of PII', description: 'The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.', sort_order: 34 },
    { control_number: '5.35', category: 'organizational', title: 'Independent review of information security', description: 'The organization\'s approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur.', sort_order: 35 },
    { control_number: '5.36', category: 'organizational', title: 'Compliance with policies, rules and standards for information security', description: 'Compliance with the organization\'s information security policy, topic-specific policies, rules and standards shall be regularly reviewed.', sort_order: 36 },
    { control_number: '5.37', category: 'organizational', title: 'Documented operating procedures', description: 'Operating procedures for information processing facilities shall be documented and made available to personnel who need them.', sort_order: 37 },
    { control_number: '6.1', category: 'people', title: 'Screening', description: 'Background verification checks on all candidates to become personnel shall be carried out prior to joining the organization and on an ongoing basis taking into consideration applicable laws, regulations and ethics and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.', sort_order: 1 },
    { control_number: '6.2', category: 'people', title: 'Terms and conditions of employment', description: 'The employment contractual agreements shall state the personnel\'s and the organization\'s responsibilities for information security.', sort_order: 2 },
    { control_number: '6.3', category: 'people', title: 'Information security awareness, education and training', description: 'Personnel of the organization and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organization\'s information security policy, topic-specific policies and procedures, as relevant for their job function.', sort_order: 3 },
    { control_number: '6.4', category: 'people', title: 'Disciplinary process', description: 'A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.', sort_order: 4 },
    { control_number: '6.5', category: 'people', title: 'Responsibilities after termination or change of employment', description: 'Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.', sort_order: 5 },
    { control_number: '6.6', category: 'people', title: 'Confidentiality or non-disclosure agreements', description: 'Confidentiality or non-disclosure agreements reflecting the organization\'s needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.', sort_order: 6 },
    { control_number: '6.7', category: 'people', title: 'Remote working', description: 'Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization\'s premises.', sort_order: 7 },
    { control_number: '6.8', category: 'people', title: 'Information security event reporting', description: 'The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.', sort_order: 8 },
    { control_number: '7.1', category: 'physical', title: 'Physical security perimeters', description: 'Security perimeters shall be defined and used to protect areas that contain information and other associated assets.', sort_order: 1 },
    { control_number: '7.2', category: 'physical', title: 'Physical entry', description: 'Secure areas shall be protected by appropriate entry controls and access points.', sort_order: 2 },
    { control_number: '7.3', category: 'physical', title: 'Securing offices, rooms and facilities', description: 'Physical security for offices, rooms and facilities shall be designed and implemented.', sort_order: 3 },
    { control_number: '7.4', category: 'physical', title: 'Physical security monitoring', description: 'Premises shall be continuously monitored for unauthorized physical access.', sort_order: 4 },
    { control_number: '7.5', category: 'physical', title: 'Protecting against physical and environmental threats', description: 'Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.', sort_order: 5 },
    { control_number: '7.6', category: 'physical', title: 'Working in secure areas', description: 'Security measures for working in secure areas shall be designed and implemented.', sort_order: 6 },
    { control_number: '7.7', category: 'physical', title: 'Clear desk and clear screen', description: 'Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.', sort_order: 7 },
    { control_number: '7.8', category: 'physical', title: 'Equipment siting and protection', description: 'Equipment shall be sited securely and protected.', sort_order: 8 },
    { control_number: '7.9', category: 'physical', title: 'Security of assets off-premises', description: 'Off-site assets shall be protected.', sort_order: 9 },
    { control_number: '7.10', category: 'physical', title: 'Storage media', description: 'Storage media shall be managed through its life cycle of acquisition, use, transportation and disposal in accordance with the organization\'s classification scheme and handling requirements.', sort_order: 10 },
    { control_number: '7.11', category: 'physical', title: 'Supporting utilities', description: 'Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.', sort_order: 11 },
    { control_number: '7.12', category: 'physical', title: 'Cabling security', description: 'Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.', sort_order: 12 },
    { control_number: '7.13', category: 'physical', title: 'Equipment maintenance', description: 'Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.', sort_order: 13 },
    { control_number: '7.14', category: 'physical', title: 'Secure disposal or re-use of equipment', description: 'Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.', sort_order: 14 },
    { control_number: '8.1', category: 'technological', title: 'User endpoint devices', description: 'Information stored on, processed by or accessible via user endpoint devices shall be protected.', sort_order: 1 },
    { control_number: '8.2', category: 'technological', title: 'Privileged access rights', description: 'The allocation and use of privileged access rights shall be restricted and managed.', sort_order: 2 },
    { control_number: '8.3', category: 'technological', title: 'Information access restriction', description: 'Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.', sort_order: 3 },
    { control_number: '8.4', category: 'technological', title: 'Access to source code', description: 'Read and write access to source code, development tools and software libraries shall be appropriately managed.', sort_order: 4 },
    { control_number: '8.5', category: 'technological', title: 'Secure authentication', description: 'Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.', sort_order: 5 },
    { control_number: '8.6', category: 'technological', title: 'Capacity management', description: 'The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.', sort_order: 6 },
    { control_number: '8.7', category: 'technological', title: 'Protection against malware', description: 'Protection against malware shall be implemented and supported by appropriate user awareness.', sort_order: 7 },
    { control_number: '8.8', category: 'technological', title: 'Management of technical vulnerabilities', description: 'Information about technical vulnerabilities of information systems in use shall be obtained, the organization\'s exposure to such vulnerabilities shall be evaluated and appropriate measures shall be taken.', sort_order: 8 },
    { control_number: '8.9', category: 'technological', title: 'Configuration management', description: 'Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.', sort_order: 9 },
    { control_number: '8.10', category: 'technological', title: 'Information deletion', description: 'Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.', sort_order: 10 },
    { control_number: '8.11', category: 'technological', title: 'Data masking', description: 'Data masking shall be used in accordance with the organization\'s topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.', sort_order: 11 },
    { control_number: '8.12', category: 'technological', title: 'Data leakage prevention', description: 'Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.', sort_order: 12 },
    { control_number: '8.13', category: 'technological', title: 'Information backup', description: 'Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.', sort_order: 13 },
    { control_number: '8.14', category: 'technological', title: 'Redundancy of information processing facilities', description: 'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.', sort_order: 14 },
    { control_number: '8.15', category: 'technological', title: 'Logging', description: 'Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.', sort_order: 15 },
    { control_number: '8.16', category: 'technological', title: 'Monitoring activities', description: 'Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.', sort_order: 16 },
    { control_number: '8.17', category: 'technological', title: 'Clock synchronization', description: 'The clocks of information processing systems used by the organization shall be synchronized to approved time sources.', sort_order: 17 },
    { control_number: '8.18', category: 'technological', title: 'Use of privileged utility programs', description: 'The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled.', sort_order: 18 },
    { control_number: '8.19', category: 'technological', title: 'Installation of software on operational systems', description: 'Procedures and measures shall be implemented to securely manage software installation on operational systems.', sort_order: 19 },
    { control_number: '8.20', category: 'technological', title: 'Networks security', description: 'Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.', sort_order: 20 },
    { control_number: '8.21', category: 'technological', title: 'Security of network services', description: 'Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.', sort_order: 21 },
    { control_number: '8.22', category: 'technological', title: 'Segregation of networks', description: 'Groups of information services, users and information systems shall be segregated in the organization\'s networks.', sort_order: 22 },
    { control_number: '8.23', category: 'technological', title: 'Web filtering', description: 'Access to external websites shall be managed to reduce exposure to malicious content.', sort_order: 23 },
    { control_number: '8.24', category: 'technological', title: 'Use of cryptography', description: 'Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.', sort_order: 24 },
    { control_number: '8.25', category: 'technological', title: 'Secure development life cycle', description: 'Rules for the secure development of software and systems shall be established and applied.', sort_order: 25 },
    { control_number: '8.26', category: 'technological', title: 'Application security requirements', description: 'Information security requirements shall be identified, specified and approved when developing or acquiring applications.', sort_order: 26 },
    { control_number: '8.27', category: 'technological', title: 'Secure system architecture and engineering principles', description: 'Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development and integration activities.', sort_order: 27 },
    { control_number: '8.28', category: 'technological', title: 'Secure coding', description: 'Secure coding principles shall be applied to software development.', sort_order: 28 },
    { control_number: '8.29', category: 'technological', title: 'Security testing in development and acceptance', description: 'Security testing processes shall be defined and implemented in the development life cycle.', sort_order: 29 },
    { control_number: '8.30', category: 'technological', title: 'Outsourced development', description: 'The organization shall direct, monitor and review the activities related to outsourced system development.', sort_order: 30 },
    { control_number: '8.31', category: 'technological', title: 'Separation of development, test and production environments', description: 'Development, testing and production environments shall be separated and secured.', sort_order: 31 },
    { control_number: '8.32', category: 'technological', title: 'Change management', description: 'Changes to information processing facilities and information systems shall be subject to change management procedures.', sort_order: 32 },
    { control_number: '8.33', category: 'technological', title: 'Test information', description: 'Test information shall be appropriately selected, protected and managed.', sort_order: 33 },
    { control_number: '8.34', category: 'technological', title: 'Protection of information systems during audit testing', description: 'Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.', sort_order: 34 },
];
export default class Iso27001Seeder extends BaseSeeder {
    async run() {
        await db.rawQuery('SET FOREIGN_KEY_CHECKS=0');
        await db.rawQuery('TRUNCATE TABLE iso27001_clause_evidence');
        await db.rawQuery('TRUNCATE TABLE iso27001_clause_assignments');
        await db.rawQuery('TRUNCATE TABLE iso27001_controls');
        await db.rawQuery('TRUNCATE TABLE iso27001_clauses');
        await db.rawQuery('SET FOREIGN_KEY_CHECKS=1');
        const topLevel = CLAUSES.filter((c) => !c.parent_number);
        const midLevel = CLAUSES.filter((c) => c.parent_number && !c.parent_number.includes('.'));
        const subLevel = CLAUSES.filter((c) => c.parent_number && c.parent_number.includes('.') && c.parent_number.split('.').length === 2);
        const deepLevel = CLAUSES.filter((c) => c.parent_number && c.parent_number.split('.').length === 3);
        const idMap = {};
        for (const clause of topLevel) {
            const [row] = await db.table('iso27001_clauses').insert({
                parent_id: null,
                clause_number: clause.clause_number,
                title: clause.title,
                description: clause.description,
                sort_order: clause.sort_order,
                created_at: new Date(),
                updated_at: new Date(),
            });
            idMap[clause.clause_number] = row;
        }
        for (const clause of midLevel) {
            const [row] = await db.table('iso27001_clauses').insert({
                parent_id: idMap[clause.parent_number],
                clause_number: clause.clause_number,
                title: clause.title,
                description: clause.description,
                sort_order: clause.sort_order,
                created_at: new Date(),
                updated_at: new Date(),
            });
            idMap[clause.clause_number] = row;
        }
        for (const clause of subLevel) {
            const [row] = await db.table('iso27001_clauses').insert({
                parent_id: idMap[clause.parent_number],
                clause_number: clause.clause_number,
                title: clause.title,
                description: clause.description,
                sort_order: clause.sort_order,
                created_at: new Date(),
                updated_at: new Date(),
            });
            idMap[clause.clause_number] = row;
        }
        for (const clause of deepLevel) {
            await db.table('iso27001_clauses').insert({
                parent_id: idMap[clause.parent_number],
                clause_number: clause.clause_number,
                title: clause.title,
                description: clause.description,
                sort_order: clause.sort_order,
                created_at: new Date(),
                updated_at: new Date(),
            });
        }
        for (const control of CONTROLS) {
            await db.table('iso27001_controls').insert({
                control_number: control.control_number,
                category: control.category,
                title: control.title,
                description: control.description,
                sort_order: control.sort_order,
                created_at: new Date(),
                updated_at: new Date(),
            });
        }
        console.log(`ISO 27001 seeded: ${CLAUSES.length} clauses, ${CONTROLS.length} controls.`);
    }
}
//# sourceMappingURL=iso27001_seeder.js.map